export const data = {
  products: [
    {
      name: 'Free shirt',
      slug: 'free-shirt',
      category: 'Shirt',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A Really Good Shirt',
    },
    {
      name: 'Fit shirt',
      slug: 'fit-shirt',
      category: 'Shirt',
      image: '/images/shirt2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A Really Good Shirt',
    },
    {
      name: 'Slim shirt',
      slug: 'slim-shirt',
      category: 'Shirt',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.9,
      numReviews: 10,
      countInStock: 20,
      description: 'A Really Good Shirt',
    },
    {
      name: 'Free Pants',
      slug: 'free-Pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 80,
      brand: 'Kamon',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart Good Shirt',
    },
    {
      name: 'fit pants',
      slug: 'fit-Pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 70,
      rating: 4.5,
      brand: 'Kamon',
      numReviews: 10,
      countInStock: 20,
      description: 'A Really Good Shirt',
    },
    {
      name: 'slim pants',
      slug: 'slim-Pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 70,
      rating: 4.5,
      brand: 'Kamon',
      numReviews: 10,
      countInStock: 20,
      description: 'A Really Good Shirt',
    },
  ],
};
